// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface IFullOrder {
  id: string;
  orderItems: OrderItem[];
  orderSubTotal: string;
  total: string;
  isReady: boolean;
  nota: null | string;
  mesa: string;
  createdAt: string;
  updatedAt: string;
  user: User;
}

export interface User {
  id: string;
  userName: string;
  fullName: string;
  isActive: boolean;
  roles: string[];
}

export interface IOrder {
  orderItems: OrderItem[];
  orderSubTotal: number;
  total: number;
  nota?: string;
  mesa?: string;
}

export interface OrderItem {
  id: string;
  titulo: string;
  imagen: string;
  precio: number;
  cantidad: number;
  subTotal: number;
}
